x = input()
xone,xtwo,xthree,xfour,xfive,xsix = x.split(" ")
x1change = 1 - int(xone)
x2change = 1 - int(xtwo)
x3change = 2 - int(xthree)
x4change = 2 - int(xfour)
x5change = 2 - int(xfive)
x6change = 8 - int(xsix)
print(str(x1change) + " " + str(x2change) + " " + str(x3change) + " " + str(x4change) + " " + str(x5change) + " " + str(x6change))